backend:
  name: github
  repo: InkBrownell/kitchenthink
  branch: main
media_folder: static/assets
public_folder: /assets
publish_mode: editorial_workflow
collections:
  - name: blog
    label: Blog
    folder: src/cms/blog
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
