# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push


jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Up Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install Clean Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: public/
        remote_path: /home/kitchenthink/kitchenth.ink/
        remote_host: kitchenth.ink
        remote_user: kitchenthink
        remote_key: ${{ secrets.DEPLOY_KEY }}
